// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDESLhN7eziFKpOJ95JQqMi_b6BqwIrKYM',
    appId: '1:463224635997:web:9ed45fde21e24e11c743b4',
    messagingSenderId: '463224635997',
    projectId: 'learning-portal-49d80',
    authDomain: 'learning-portal-49d80.firebaseapp.com',
    storageBucket: 'learning-portal-49d80.firebasestorage.app',
    measurementId: 'G-CF4G76WGX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-u2H5t9OLQjkBfVR_acVZ-5Jd7aYh1c',
    appId: '1:463224635997:android:84fa9b3f9566f75fc743b4',
    messagingSenderId: '463224635997',
    projectId: 'learning-portal-49d80',
    storageBucket: 'learning-portal-49d80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpbnYmSyWRwRPMsl2-fKitunVnMPS0auo',
    appId: '1:463224635997:ios:adec535090e60683c743b4',
    messagingSenderId: '463224635997',
    projectId: 'learning-portal-49d80',
    storageBucket: 'learning-portal-49d80.firebasestorage.app',
    iosBundleId: 'uk.co.gcsewithrosi.portal.leariningPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpbnYmSyWRwRPMsl2-fKitunVnMPS0auo',
    appId: '1:463224635997:ios:adec535090e60683c743b4',
    messagingSenderId: '463224635997',
    projectId: 'learning-portal-49d80',
    storageBucket: 'learning-portal-49d80.firebasestorage.app',
    iosBundleId: 'uk.co.gcsewithrosi.portal.leariningPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDESLhN7eziFKpOJ95JQqMi_b6BqwIrKYM',
    appId: '1:463224635997:web:8d835e5cf87b5359c743b4',
    messagingSenderId: '463224635997',
    projectId: 'learning-portal-49d80',
    authDomain: 'learning-portal-49d80.firebaseapp.com',
    storageBucket: 'learning-portal-49d80.firebasestorage.app',
    measurementId: 'G-ZWS24PCSDY',
  );
}
