-- One-time OTP codes to authorize moving mobile app login to a new device.
-- Single use only (no expiry). Generated by school admin on the web.

CREATE TABLE IF NOT EXISTS `mobile_app_device_transfer_otp` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `actor_type` varchar(32) NOT NULL COMMENT 'staff|portal_user|app_parent_user',
  `actor_id` int(11) UNSIGNED NOT NULL,
  `otp_hash` varchar(255) NOT NULL COMMENT 'bcrypt hash of 6-digit code',
  `expires_at` datetime DEFAULT NULL COMMENT 'unused; kept for schema compatibility',
  `used_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by_staff_id` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_actor_active` (`actor_type`, `actor_id`, `used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
